spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/step-trace
    username: mysql
    password: mysql
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

feign:
  client:
    kakao:
      name: kakaoLogin
      base-url: https://kauth.kakao.com
      auth-url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=a911a9cd4ee96a1c1d463050751ed765&redirect_uri=http://localhost:8080/auth/kakao/callback
      token-uri: /oauth/token
      oicd-open-key-uri: /.well-known/jwks.json
      rest-api-key: a911a9cd4ee96a1c1d463050751ed765
      redirect-uri: http://localhost:8080/auth/kakao/callback
      grant-type: authorization_code
      oicd-base-url: https://kapi.kakao.com
      oicd-userinfo-uri: /v1/oidc/userinfo
    google:
      name: googleLogin
      auth-url: https://accounts.google.com/o/oauth2/auth?client_id=441196104479-3kqc9h08p676gote5hq4truqiijfdfco.apps.googleusercontent.com&redirect_uri=http://localhost:8080/auth/google/callback&response_type=code&scope=openid+email+profile
      token-url: https://oauth2.googleapis.com
      userinfo-url: https://www.googleapis.com
      client-id: 441196104479-3kqc9h08p676gote5hq4truqiijfdfco.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/auth/google/callback
      grant-type: authorization_code
      iss: https://accounts.google.com
      oicd-open-key-url: https://www.googleapis.com