spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

feign:
  client:
    kakao:
      name: kakaoLogin
      base-url: https://kauth.kakao.com
      auth-url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=${KAKAO_REST_API_KEY}&redirect_uri=${KAKAO_REDIRECT_URI}
      token-uri: /oauth/token
      oicd-open-key-uri: /.well-known/jwks.json
      rest-api-key: ${KAKAO_REST_API_KEY}
      native_key: ${KAKAO_NATIVE_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      grant-type: authorization_code
      oicd-base-url: https://kapi.kakao.com
      oicd-userinfo-uri: /v1/oidc/userinfo
    google:
      name: googleLogin
      auth-url: https://accounts.google.com/o/oauth2/auth?client_id=${GOOGLE_CLIENT_ID}&redirect_uri=${GOOGLE_REDIRECT_URI}&response_type=code&scope=openid+email+profile
      token-url: https://oauth2.googleapis.com
      userinfo-url: https://www.googleapis.com
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      grant-type: authorization_code
      iss: https://accounts.google.com
      oicd-open-key-url: https://www.googleapis.com

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}
  prefix: ${JWT_PREFIX}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.steptrace: DEBUG
    root: INFO

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}